"""Minimal bounded Autodesk 3DS mesh reader used for recovery conversion."""

from __future__ import annotations

import dataclasses
import struct
from pathlib import Path
from typing import Iterator


class ThreeDSError(ValueError):
    pass


@dataclasses.dataclass
class Mesh:
    name: str
    vertices: list[tuple[float, float, float]] = dataclasses.field(default_factory=list)
    faces: list[tuple[int, int, int]] = dataclasses.field(default_factory=list)
    texcoords: list[tuple[float, float]] = dataclasses.field(default_factory=list)


def chunks(data: bytes, start: int, end: int) -> Iterator[tuple[int, int, int]]:
    cursor = start
    while cursor < end:
        if cursor + 6 > end:
            raise ThreeDSError("truncated 3DS chunk header")
        chunk_id, length = struct.unpack_from("<HI", data, cursor)
        if length < 6 or cursor + length > end:
            raise ThreeDSError(f"invalid 3DS chunk 0x{chunk_id:04x} length {length}")
        yield chunk_id, cursor + 6, cursor + length
        cursor += length


def cstring(data: bytes, start: int, end: int) -> tuple[str, int]:
    terminator = data.find(b"\0", start, end)
    if terminator < 0:
        raise ThreeDSError("unterminated 3DS object name")
    return data[start:terminator].decode("cp1252", errors="replace"), terminator + 1


def parse_trimesh(data: bytes, start: int, end: int, mesh: Mesh) -> None:
    for chunk_id, body, chunk_end in chunks(data, start, end):
        if chunk_id == 0x4110:
            if body + 2 > chunk_end:
                raise ThreeDSError("truncated 3DS vertex count")
            count = struct.unpack_from("<H", data, body)[0]
            needed = body + 2 + count * 12
            if needed > chunk_end:
                raise ThreeDSError("3DS vertex array exceeds chunk")
            mesh.vertices = [struct.unpack_from("<fff", data, body + 2 + index * 12) for index in range(count)]
        elif chunk_id == 0x4120:
            if body + 2 > chunk_end:
                raise ThreeDSError("truncated 3DS face count")
            count = struct.unpack_from("<H", data, body)[0]
            needed = body + 2 + count * 8
            if needed > chunk_end:
                raise ThreeDSError("3DS face array exceeds chunk")
            mesh.faces = [struct.unpack_from("<HHH", data, body + 2 + index * 8) for index in range(count)]
        elif chunk_id == 0x4140:
            if body + 2 > chunk_end:
                raise ThreeDSError("truncated 3DS texture-coordinate count")
            count = struct.unpack_from("<H", data, body)[0]
            needed = body + 2 + count * 8
            if needed > chunk_end:
                raise ThreeDSError("3DS texture-coordinate array exceeds chunk")
            mesh.texcoords = [struct.unpack_from("<ff", data, body + 2 + index * 8) for index in range(count)]


def parse_editor(data: bytes, start: int, end: int, meshes: list[Mesh]) -> None:
    for chunk_id, body, chunk_end in chunks(data, start, end):
        if chunk_id == 0x4000:
            name, nested = cstring(data, body, chunk_end)
            mesh = Mesh(name=name)
            for nested_id, nested_body, nested_end in chunks(data, nested, chunk_end):
                if nested_id == 0x4100:
                    parse_trimesh(data, nested_body, nested_end, mesh)
            if mesh.vertices and mesh.faces:
                if any(index >= len(mesh.vertices) for face in mesh.faces for index in face):
                    raise ThreeDSError(f"face index outside vertex array in {name}")
                meshes.append(mesh)
        elif chunk_id in {0x3D3D, 0x4D4D}:
            parse_editor(data, body, chunk_end, meshes)


def load_3ds(path: Path) -> list[Mesh]:
    data = path.read_bytes()
    if len(data) < 6:
        raise ThreeDSError("truncated 3DS file")
    root_id, length = struct.unpack_from("<HI", data, 0)
    if root_id != 0x4D4D:
        raise ThreeDSError(f"missing 3DS main chunk: 0x{root_id:04x}")
    if length < 6 or length > len(data):
        raise ThreeDSError("invalid 3DS main chunk length")
    meshes: list[Mesh] = []
    parse_editor(data, 6, length, meshes)
    if not meshes:
        raise ThreeDSError("3DS file contains no triangle mesh")
    return meshes


def write_obj(meshes: list[Mesh], destination: Path) -> dict[str, int]:
    lines = ["# Generated by tools/legacy_3ds.py"]
    vertex_offset = 1
    vertices = faces = 0
    for mesh in meshes:
        lines.append(f"o {mesh.name.replace(chr(10), '_').replace(chr(13), '_')}")
        lines.extend(f"v {x:.9g} {y:.9g} {z:.9g}" for x, y, z in mesh.vertices)
        has_uv = len(mesh.texcoords) == len(mesh.vertices)
        if has_uv:
            lines.extend(f"vt {u:.9g} {1.0 - v:.9g}" for u, v in mesh.texcoords)
        for a, b, c in mesh.faces:
            indices = (a + vertex_offset, b + vertex_offset, c + vertex_offset)
            if has_uv:
                lines.append("f " + " ".join(f"{index}/{index}" for index in indices))
            else:
                lines.append("f " + " ".join(str(index) for index in indices))
        vertex_offset += len(mesh.vertices)
        vertices += len(mesh.vertices)
        faces += len(mesh.faces)
    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return {"meshes": len(meshes), "vertices": vertices, "faces": faces}
